version: "1.0"
info:
  model: int-scaffold
packages:
- name: Dada5Project
  gitServerName: sumitaShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
services:
- serviceName: project.dada5.integrations:test1
  packages:
  - name: Dada5Project
    version: "1.0"
